addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.7")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.25")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.13.0")
