addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.8.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.8.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.2")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.43")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.4")
